# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.5
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  exclude:
    - arch: x86
      os: osx
  include:
    - stage: Documentation
      julia: 1
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: doctest
          using FieldTracer
          doctest(FieldTracer)
          include("docs/make.jl")'
      after_success: skip
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
