name = "FieldTracer"
uuid = "05065131-34d1-456a-ba22-faf972bb2934"
authors = ["Hongyang Zhou <hyzhou@umich.edu>"]
version = "0.1.15"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
Meshes = "0.44, 0.45"
MuladdMacro = "0.2"
PrecompileTools = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
